### ISSUE TITLE
Add release for Mac OS X

### ISSUE THREAD

**Issue by swisener** [jgoldshlag/padherder_proxy#30]
I spent several hours getting this project running on OS X. Is there any plan to make releases for Mac? In the meantime, here's how to get the project up and running on El Capitan:
# Install basic development tools, if necessary

Install XCode if you don't already have it:

`xcode-select --install`

Install Homebrew by following instructions at http://brew.sh/
# Get a non-system version of python using Homebrew.

The one that comes with El Capitan has some development libraries that cannot be upgraded for some reason, even when running as root. I'm not a Python expert, so I'm not exactly sure why.

`brew install python`

Source your profile, or just kill your Terminal and relaunch. Make sure:

`which python`

returns /usr/local/bin/python
# Install the "easy" modules

Note that the latest version of mitmproxy _does not_ work with padherder_proxy; you should explicitly install version 0.16

`pip install mitmproxy==0.16`
`pip install requests dnslib`
# Install wxPython

Make sure you are an the 3.0 branch of wxWidgets; the latest development version _does not_ work. Also the latest published stable version (3.0.2) has an unpatched bug for El Capitan, so you need to get the source from Github.

`git clone https://github.com/wxWidgets/wxWidgets.git`
`cd wxWidgets`
`git checkout WX_3_0_BRANCH`
`cd ..`
`git clone https://github.com/wxWidgets/wxPython.git`
`cd wxPython`
`python build-wxpython.py --osx_cocoa --install`
# Checkout padherder_proxy and run it

Note that you need to be root (run under sudo) for the DNS to work.

`git clone https://github.com/jgoldshlag/padherder_proxy.git`
`cd padherder_proxy`
`sudo python padherder_proxy.py`

**Comment by jgoldshlag** [comment]
Thanks for the install instructions. My wife has a Mac, so I suppose I have no excuse not to build a Mac release. I'll see about getting that running sometime soon

**Comment by KinmarX** [comment]
I have no issues running through the steps listed above until the very end. When running "sudo python padherder_proxy.py" I get the following error:

> Traceback (most recent call last):
  File "padherder_proxy.py", line 17, in <module>
    from libmproxy import controller, proxy, flow, dump, cmdline, contentviews
ImportError: No module named libmproxy

Tried searching for help but nothing really seems to work, any ideas?

**Comment by jgoldshlag** [comment]
I had a bunch of trouble getting this up and running on an RL friend's macbook. I don't actually even remember what we ended up doing to get it all working, but just the above wasn't enough.

**Comment by swisener** [comment]
For what it's worth, I am on commit a1e9a3a of padherder_proxy. I tried pulling the latest commit and it didn't work, so I just reverted back; I didn't have the patience to debug it. I have also upgraded to Sierra since I wrote the original instructions, and the code at that commit still works fine. One additional step is you must turn on Sharing of some sort in System Preferences -> Sharing. I think any one will work (I have Remote Login enabled).

For reference, here are the versions of all modules that I have installed:

argh (0.26.2)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
blinker (1.4)
brotlipy (0.6.0)
certifi (2016.9.26)
cffi (1.8.3)
click (6.6)
ConfigArgParse (0.10.0)
construct (2.5.3)
cryptography (1.2.3)
cssutils (1.0.1)
dnslib (0.9.6)
EditorConfig (0.12.1)
enum34 (1.1.6)
Flask (0.11.1)
h2 (2.1.5)
hpack (2.3.0)
html2text (2016.1.8)
hyperframe (3.2.0)
idna (2.1)
ipaddress (1.0.17)
itsdangerous (0.24)
Jinja2 (2.8)
jsbeautifier (1.6.4)
lxml (3.5.0)
MarkupSafe (0.23)
mitmproxy (0.16)
netlib (0.16)
passlib (1.6.5)
pathtools (0.1.2)
Pillow (3.1.2)
pip (9.0.0)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (0.15.1)
pyparsing (2.1.10)
pyperclip (1.5.27)
PyYAML (3.12)
requests (2.11.1)
setuptools (28.8.0)
singledispatch (3.4.0.3)
six (1.10.0)
tornado (4.3)
typing (3.5.2.2)
urwid (1.3.1)
watchdog (0.8.3)
Werkzeug (0.11.11)
wheel (0.29.0)

**Comment by nholthaus** [comment]
I originally had the same error as @KinmarX (using commit a1e9a3a). The error seemed to be caused by a missing dependency (libjpeg, required by wheel, required by pillow, required by mitmproxy). The revised set of instructions that actually worked for me are:

1. `xcode-select --install` (I pressed the 'get xcode' button that was shown after this command)
2. `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
3. `brew install python`
4. Relaunch terminal
5. **`brew install libjpeg` (new step)**
6. `pip install mitmproxy==0.16`
7. `pip install requests dnslib`
8. `git clone https://github.com/wxWidgets/wxWidgets.git`
9. `cd wxWidgets`
10. `git checkout WX_3_0_BRANCH`
11. `cd ..`
12. `git clone https://github.com/wxWidgets/wxPython.git`
13. `cd wxPython`
14. `python build-wxpython.py --osx_cocoa --install`
15. `git clone https://github.com/jgoldshlag/padherder_proxy.git`
16. `cd padherder_proxy`
17. **`git checkout  a1e9a3a` (new step)**
18. `sudo python padherder_proxy.py`

**Comment by AnthonyChen00** [comment]
I get this error when i try sudo python padherder_proxy.py

> Traceback (most recent call last):
  File "padherder_proxy.py", line 597, in <module>
    main()
  File "padherder_proxy.py", line 577, in main
    frame = MainWindow(None, "Padherder Proxy v%s" % PH_PROXY_VERSION)
  File "padherder_proxy.py", line 496, in __init__
    self.main_tab = MainTab(nb)
  File "padherder_proxy.py", line 286, in __init__
    host = config.Read("host") or socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by swisener** [comment]
Try turning on some sort of Sharing in System Preferences; for example, Remote Login.

**Comment by shiftb** [comment]
I'm having the same issue as tomokoNALS is after following nholthaus' instructions. Turned Remote Login off and then back on again. Didn't seem to make a difference. Any ideas?

`macOS Sierra 10.12.4 Beta (16E163f)`

**Comment by dongwoo1005** [comment]
Changing all the lines of `host = config.Read("host") or socket.gethostbyname(socket.gethostname())`. to `host = config.Read("host") or socket.gethostbyname('').` fixes the error mentioned by @tomokoNALS . It may be a hack, but it works for the sake of running it.
