### ISSUE TITLE
TypeError: 'NoneType' object is not iterable during do_sync.

### ISSUE THREAD

**Issue by cyril-vandyke** [jgoldshlag/padherder_proxy#45]
Error message is as follows:

```
Got DNS Request
Got HTTPS request, forwarding
Got HTTPS request, forwarding
Got box data, processing...
Downloaded full monster data
Got HTTPS request, forwarding
Got mail data, processing...
Downloaded current padherder box
Skipping sync of team 5 because a new monster is on the team. Please sync again
Error doing team sync:
Traceback (most recent call last):
  File "padherder_sync.py", line 206, in do_sync_teams
KeyError: 's07'


Please report this error on github
Error doing sync:
Traceback (most recent call last):
  File "padherder_sync.py", line 421, in do_sync
TypeError: 'NoneType' object is not iterable


Please report this error on github
```

**Comment by cyril-vandyke** [comment]
If anyone else is running into this issue, downgrading to version 2.6 seems to be a functional workaround apart from team syncing.

I attempted to run v.2.8 from source with the team-sync functionality commented out but ran into issues after the program started receiving HTTPS requests.

**Comment by Synnite** [comment]
By any chance, did you recently hit Rank 200? That's when I started getting this error. I figured it's because of having an extra team that padherder might not be programmed for.

**Comment by cyril-vandyke** [comment]
@Synnite Actually, yeah. That's exactly when it started happening. Initially I thought that it was caused by me never having actually set a team in the slot, but that doesn't fix it.

**Comment by jgoldshlag** [comment]
Sorry, I was on vacation when this popped up for you guys. I think I have a fix in hand, but I am little confused. It looks like it should have happened when you got the ability to have a new team but hadn't set up that new team slot in game. If you create a team there, it should work fine. If that doesn't fix things, please let me know. I'll cut a new release with the fix in the hope that it fixes things anyway though.

**Comment by Synnite** [comment]
In case anyone was wondering, the issue was resolved with the fix. Thank you!
