### ISSUE TITLE
Error with Machine Hera

### ISSUE THREAD

**Issue by Chamiel** [jgoldshlag/padherder_proxy#8]
I get this error when I'm syncing:
Traceback (most recent call last):
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 183, in do_sync
  File "C:\Users\Josh\Dropbox\padherder_proxy\padherder_sync.py", line 35, in xp_at_level
TypeError: object of type 'NoneType' has no len()

I looked into the code, and found that this happens because there is no exp curve for machine hera, so it returns an error.

**Comment by jgoldshlag** [comment]
Yup, fixed in the latest release, thanks for reporting it!
